name: Feature Request
description: Suggest a new feature or improvement
title: "[feat]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What does the current behavior fail to handle?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should Thirdwatch handle this?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought of

  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to implement this?
      options:
        - "Yes — I will submit a PR"
        - "Maybe — with guidance"
        - "No — just suggesting"
    validations:
      required: true
